//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;
using System.Reflection;

[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyTitleAttribute("XviD4PSP")]
[assembly: AssemblyDescriptionAttribute("AviSynth-based MultiMedia Converter")]
[assembly: AssemblyCompanyAttribute("Winnydows Inc. & FCP Team")]
[assembly: AssemblyProductAttribute("XviD4PSP 5")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2007-2008 Winnydows,  2009-2011 fcp team")]
[assembly: AssemblyVersionAttribute("5.10.263.0")]
[assembly: AssemblyFileVersionAttribute("5.10.263.0")]
[assembly: AssemblyTrademarkAttribute("")]
