//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;
using System.Reflection;

[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyTitleAttribute("XviD4PSP")]
[assembly: AssemblyDescriptionAttribute("Multi format video converter for PSP, PS3, iPod, BlackBerry, PC.")]
[assembly: AssemblyCompanyAttribute("Winnydows Inc. and OtherPeople")]
[assembly: AssemblyProductAttribute("XviD4PSP")]
[assembly: AssemblyCopyrightAttribute("Copyright © Winnydows 2008 and  OtherPeople 2009")]
[assembly: AssemblyVersionAttribute("5.0.37.6")]
[assembly: AssemblyFileVersionAttribute("5.0.37.6")]
[assembly: AssemblyTrademarkAttribute("rev74")]
