//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XviD4PSP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PowerManagementResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PowerManagementResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XviD4PSP.classes.PowerManagement.PowerManagementResource", typeof(PowerManagementResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument powerSchemeTitle cannot be null..
        /// </summary>
        internal static string ArgumentNullMessage {
            get {
                return ResourceManager.GetString("ArgumentNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string ChoiceAutomatic {
            get {
                return ResourceManager.GetString("ChoiceAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string ChoiceDisabled {
            get {
                return ResourceManager.GetString("ChoiceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Nothing.
        /// </summary>
        internal static string ChoiceDoNothing {
            get {
                return ResourceManager.GetString("ChoiceDoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string ChoiceEnabled {
            get {
                return ResourceManager.GetString("ChoiceEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Power Saving.
        /// </summary>
        internal static string ChoiceLowPowerSaving {
            get {
                return ResourceManager.GetString("ChoiceLowPowerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Performance.
        /// </summary>
        internal static string ChoiceMaximumPerformance {
            get {
                return ResourceManager.GetString("ChoiceMaximumPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Power Saving.
        /// </summary>
        internal static string ChoiceMaximumPowerSaving {
            get {
                return ResourceManager.GetString("ChoiceMaximumPowerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Power Saving.
        /// </summary>
        internal static string ChoiceMediumPowerSaving {
            get {
                return ResourceManager.GetString("ChoiceMediumPowerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate Power Saving.
        /// </summary>
        internal static string ChoiceModeratePowerSaving {
            get {
                return ResourceManager.GetString("ChoiceModeratePowerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string ChoiceNever {
            get {
                return ResourceManager.GetString("ChoiceNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ChoiceNone {
            get {
                return ResourceManager.GetString("ChoiceNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent Idle.
        /// </summary>
        internal static string ChoicePreventIdle {
            get {
                return ResourceManager.GetString("ChoicePreventIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Away Mode.
        /// </summary>
        internal static string ChoiceUseAwayMode {
            get {
                return ResourceManager.GetString("ChoiceUseAwayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete default or active power schemes..
        /// </summary>
        internal static string DeleteSchemeMessage {
            get {
                return ResourceManager.GetString("DeleteSchemeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string ErrorInvalidGuid {
            get {
                return ResourceManager.GetString("ErrorInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorSpecifyAgrument {
            get {
                return ResourceManager.GetString("ErrorSpecifyAgrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply &apos;{0}&apos; and &apos;{1}&apos;. .
        /// </summary>
        internal static string ErrorSpecifyBothArguments {
            get {
                return ResourceManager.GetString("ErrorSpecifyBothArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument secondsTimer&apos;s value can not be greater than or equal to 315360000 seconds..
        /// </summary>
        internal static string MaximumRebootTimerValue {
            get {
                return ResourceManager.GetString("MaximumRebootTimerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument secondsTimer&apos;s value can not be greater than or equal to 315360000 seconds..
        /// </summary>
        internal static string MaximumShutdownTimerValue {
            get {
                return ResourceManager.GetString("MaximumShutdownTimerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computer does not support hibernation (power state S4)..
        /// </summary>
        internal static string NoHibernationSupport {
            get {
                return ResourceManager.GetString("NoHibernationSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have sufficient privileges to shutdown..
        /// </summary>
        internal static string NoShutdownPrivilege {
            get {
                return ResourceManager.GetString("NoShutdownPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (AC-specific).
        /// </summary>
        internal static string PostfixAcSpecific {
            get {
                return ResourceManager.GetString("PostfixAcSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (DC-specific).
        /// </summary>
        internal static string PostfixDcSpecific {
            get {
                return ResourceManager.GetString("PostfixDcSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string PostfixPercentage {
            get {
                return ResourceManager.GetString("PostfixPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        internal static string PostfixSeconds {
            get {
                return ResourceManager.GetString("PostfixSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        internal static string PowerSchemeBalancedTitle {
            get {
                return ResourceManager.GetString("PowerSchemeBalancedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High performance.
        /// </summary>
        internal static string PowerSchemeHighPerformanceTitle {
            get {
                return ResourceManager.GetString("PowerSchemeHighPerformanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified power scheme not found..
        /// </summary>
        internal static string PowerSchemeNotFound {
            get {
                return ResourceManager.GetString("PowerSchemeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power saver.
        /// </summary>
        internal static string PowerSchemePowerSaverTitle {
            get {
                return ResourceManager.GetString("PowerSchemePowerSaverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of argument shutdownMessage cannot be greater than 511 characters..
        /// </summary>
        internal static string RebootMessageLength {
            get {
                return ResourceManager.GetString("RebootMessageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}$.
        /// </summary>
        internal static string RegularExpressionGuid {
            get {
                return ResourceManager.GetString("RegularExpressionGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of argument shutdownMessage cannot be greater than 511 characters..
        /// </summary>
        internal static string ShutdownMessageLength {
            get {
                return ResourceManager.GetString("ShutdownMessageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e73a048d-bf27-4f12-9731-8b2076e8891f.
        /// </summary>
        internal static string SubgroupBatteryGuid {
            get {
                return ResourceManager.GetString("SubgroupBatteryGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0012ee47-9041-4b5d-9b77-535fba8b1442.
        /// </summary>
        internal static string SubgroupDiskGuid {
            get {
                return ResourceManager.GetString("SubgroupDiskGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7516b95f-f776-4464-8c53-06167f40cc99.
        /// </summary>
        internal static string SubgroupDisplayGuid {
            get {
                return ResourceManager.GetString("SubgroupDisplayGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9596fb26-9850-41fd-ac3e-f7c3c00afd4b.
        /// </summary>
        internal static string SubgroupMultimediaGuid {
            get {
                return ResourceManager.GetString("SubgroupMultimediaGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 501a4d13-42af-4429-9fd1-a8218c268e20.
        /// </summary>
        internal static string SubgroupPciExpressGuid {
            get {
                return ResourceManager.GetString("SubgroupPciExpressGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4f971e89-eebd-4455-a8de-9e59040e7347.
        /// </summary>
        internal static string SubgroupPowerButtonGuid {
            get {
                return ResourceManager.GetString("SubgroupPowerButtonGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54533251-82be-4824-96c1-47b60b740d00.
        /// </summary>
        internal static string SubgroupProcessorGuid {
            get {
                return ResourceManager.GetString("SubgroupProcessorGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 581a5406-53a3-4acd-af43-f685fa098e06.
        /// </summary>
        internal static string SubgroupSearchIndexingGuid {
            get {
                return ResourceManager.GetString("SubgroupSearchIndexingGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 238c9fa8-0aad-41ed-83f4-97be242c8f20.
        /// </summary>
        internal static string SubgroupSleepGuid {
            get {
                return ResourceManager.GetString("SubgroupSleepGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2a737441-1930-4402-8d77-b2bebba308a3.
        /// </summary>
        internal static string SubgroupUsbGuid {
            get {
                return ResourceManager.GetString("SubgroupUsbGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19cbb8fa-5279-450e-9fac-8a3d5fedd0c1.
        /// </summary>
        internal static string SubgroupWirelessAdapterGuid {
            get {
                return ResourceManager.GetString("SubgroupWirelessAdapterGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows32 Error Code : .
        /// </summary>
        internal static string Win32ErrorCodeMessage {
            get {
                return ResourceManager.GetString("Win32ErrorCodeMessage", resourceCulture);
            }
        }
    }
}
